var _Bar0 = new VF.Stave(10.0, 40, 600.0);
var _StaveNote1 = new VF.StaveNote({keys: ["F#/4","A/4","D/5"], duration: "16"});
_StaveNote1.addAccidental(0, new VF.Accidental("#"));
var _StaveNote2 = new VF.StaveNote({keys: ["A/4","D/5","F/5"], duration: "16"});
_StaveNote2.addAccidental(2, new VF.Accidental("n"));
var _StaveNote3 = new VF.StaveNote({keys: ["B/4"], duration: "16r"});
var _StaveNote4 = new VF.StaveNote({keys: ["B/4"], duration: "16r"});
var _StaveNote5 = new VF.StaveNote({keys: ["F#/4","A/4","D/5"], duration: "16"});
_StaveNote5.addAccidental(0, new VF.Accidental("#"));
var _StaveNote6 = new VF.StaveNote({keys: ["A/4","D/5","F/5"], duration: "16"});
_StaveNote6.addAccidental(2, new VF.Accidental("n"));
var _StaveNote7 = new VF.StaveNote({keys: ["B/4"], duration: "16r"});
var _StaveNote8 = new VF.StaveNote({keys: ["B/4"], duration: "16r"});
var _StaveNote9 = new VF.StaveNote({keys: ["F#/4","A/4","D/5"], duration: "16"});
_StaveNote9.addAccidental(0, new VF.Accidental("#"));
var _StaveNote10 = new VF.StaveNote({keys: ["A/4","D/5","F/5"], duration: "16"});
_StaveNote10.addAccidental(2, new VF.Accidental("n"));
var _StaveNote11 = new VF.StaveNote({keys: ["B/4"], duration: "16r"});
var _StaveNote12 = new VF.StaveNote({keys: ["B/4"], duration: "16r"});
var _StaveNote13 = new VF.StaveNote({keys: ["F#/4","A/4","D/5"], duration: "16"});
_StaveNote13.addAccidental(0, new VF.Accidental("#"));
var _StaveNote14 = new VF.StaveNote({keys: ["A/4","D/5","F/5"], duration: "16"});
_StaveNote14.addAccidental(2, new VF.Accidental("n"));
var _StaveNote15 = new VF.StaveNote({keys: ["B/4"], duration: "16r"});
var _StaveNote16 = new VF.StaveNote({keys: ["B/4"], duration: "16r"});
var __StaveNote_17 = [_StaveNote1,_StaveNote2,_StaveNote3,_StaveNote4,_StaveNote5,_StaveNote6,_StaveNote7,_StaveNote8,_StaveNote9,_StaveNote10,_StaveNote11,_StaveNote12,_StaveNote13,_StaveNote14,_StaveNote15,_StaveNote16];
var _Voice18 = new VF.Voice();
_Voice18.addTickables([__StaveNote_17]);
var _Formatter19 = new VF.Formatter().joinVoices([_Voice18]).format([_Voice18], 600.0);
var _Beam20 = VF.Beam.generateBeams(__StaveNote_17);
_Bar0.addClef("treble");
_Bar0.addTimeSignature("4/4");
_Bar0.setContext(ctx).draw();
_Voice18.draw(ctx, _Bar0);
_Beam20.forEach(beam => beam.setContext(ctx).draw());