var _Bar0 = new VF.Stave(10.0, 40, 600.0);
var _StaveNote1 = new VF.StaveNote({keys: ["F#/4","A/4","D/5"], duration: "16"});
_StaveNote1.addAccidental(0, new VF.Accidental("#"));
var _StaveNote2 = new VF.StaveNote({keys: ["A/4","D/5","F/5"], duration: "16"});
_StaveNote2.addAccidental(2, new VF.Accidental("n"));
var _StaveNote3 = new VF.StaveNote({keys: ["B/4"], duration: "16r"});
var _StaveNote4 = new VF.StaveNote({keys: ["B/4"], duration: "16r"});
var _StaveNote5 = new VF.StaveNote({keys: ["F#/4","A/4","D/5"], duration: "16"});
_StaveNote5.addAccidental(0, new VF.Accidental("#"));
var _StaveNote6 = new VF.StaveNote({keys: ["A/4","D/5","F/5"], duration: "16"});
_StaveNote6.addAccidental(2, new VF.Accidental("n"));
var _StaveNote7 = new VF.StaveNote({keys: ["B/4"], duration: "16r"});
var _StaveNote8 = new VF.StaveNote({keys: ["B/4"], duration: "16r"});
var _StaveNote9 = new VF.StaveNote({keys: ["F#/4","A/4","D/5"], duration: "16"});
_StaveNote9.addAccidental(0, new VF.Accidental("#"));
var _StaveNote10 = new VF.StaveNote({keys: ["A/4","D/5","F/5"], duration: "16"});
_StaveNote10.addAccidental(2, new VF.Accidental("n"));
var _StaveNote11 = new VF.StaveNote({keys: ["B/4"], duration: "16r"});
var _StaveNote12 = new VF.StaveNote({keys: ["B/4"], duration: "16r"});
var _StaveNote13 = new VF.StaveNote({keys: ["F#/4","A/4","D/5"], duration: "16"});
_StaveNote13.addAccidental(0, new VF.Accidental("#"));
var _StaveNote14 = new VF.StaveNote({keys: ["A/4","D/5","F/5"], duration: "16"});
_StaveNote14.addAccidental(2, new VF.Accidental("n"));
var _StaveNote15 = new VF.StaveNote({keys: ["B/4"], duration: "16r"});
var _StaveNote16 = new VF.StaveNote({keys: ["B/4"], duration: "16r"});
var __StaveNote_17 = [_StaveNote1,_StaveNote2,_StaveNote3,_StaveNote4,_StaveNote5,_StaveNote6,_StaveNote7,_StaveNote8,_StaveNote9,_StaveNote10,_StaveNote11,_StaveNote12,_StaveNote13,_StaveNote14,_StaveNote15,_StaveNote16];
var _Voice18 = new VF.Voice();
_Voice18.addTickables(__StaveNote_17);
var _Beam20 = VF.Beam.generateBeams(__StaveNote_17);
var _Bar21 = new VF.Stave(10.0, 150, 600.0);
var _StaveNote22 = new VF.StaveNote({keys: ["F#/4","A/4","D/5"], duration: "16"});
_StaveNote22.addAccidental(0, new VF.Accidental("#"));
var _StaveNote23 = new VF.StaveNote({keys: ["A/4","D/5","F/5"], duration: "16"});
_StaveNote23.addAccidental(2, new VF.Accidental("n"));
var _StaveNote24 = new VF.StaveNote({keys: ["B/4"], duration: "16r"});
var _StaveNote25 = new VF.StaveNote({keys: ["B/4"], duration: "16r"});
var _StaveNote26 = new VF.StaveNote({keys: ["F#/4","A/4","D/5"], duration: "16"});
_StaveNote26.addAccidental(0, new VF.Accidental("#"));
var _StaveNote27 = new VF.StaveNote({keys: ["A/4","D/5","F/5"], duration: "16"});
_StaveNote27.addAccidental(2, new VF.Accidental("n"));
var _StaveNote28 = new VF.StaveNote({keys: ["B/4"], duration: "16r"});
var _StaveNote29 = new VF.StaveNote({keys: ["B/4"], duration: "16r"});
var _StaveNote30 = new VF.StaveNote({keys: ["F#/4","A/4","D/5"], duration: "16"});
_StaveNote30.addAccidental(0, new VF.Accidental("#"));
var _StaveNote31 = new VF.StaveNote({keys: ["A/4","D/5","F/5"], duration: "16"});
_StaveNote31.addAccidental(2, new VF.Accidental("n"));
var _StaveNote32 = new VF.StaveNote({keys: ["B/4"], duration: "16r"});
var _StaveNote33 = new VF.StaveNote({keys: ["B/4"], duration: "16r"});
var _StaveNote34 = new VF.StaveNote({keys: ["F#/4","A/4","D/5"], duration: "16"});
_StaveNote34.addAccidental(0, new VF.Accidental("#"));
var _StaveNote35 = new VF.StaveNote({keys: ["A/4","D/5","F/5"], duration: "16"});
_StaveNote35.addAccidental(2, new VF.Accidental("n"));
var _StaveNote36 = new VF.StaveNote({keys: ["B/4"], duration: "16r"});
var _StaveNote37 = new VF.StaveNote({keys: ["B/4"], duration: "16r"});
var __StaveNote_38 = [_StaveNote22,_StaveNote23,_StaveNote24,_StaveNote25,_StaveNote26,_StaveNote27,_StaveNote28,_StaveNote29,_StaveNote30,_StaveNote31,_StaveNote32,_StaveNote33,_StaveNote34,_StaveNote35,_StaveNote36,_StaveNote37];
var _Voice39 = new VF.Voice();
_Voice39.addTickables(__StaveNote_38);
var _Beam41 = VF.Beam.generateBeams(__StaveNote_38);
var _Bar42 = new VF.Stave(10.0, 260, 600.0);
var _StaveNote43 = new VF.StaveNote({keys: ["F#/4","A/4","D/5"], duration: "16"});
_StaveNote43.addAccidental(0, new VF.Accidental("#"));
var _StaveNote44 = new VF.StaveNote({keys: ["A/4","D/5","F/5"], duration: "16"});
_StaveNote44.addAccidental(2, new VF.Accidental("n"));
var _StaveNote45 = new VF.StaveNote({keys: ["B/4"], duration: "16r"});
var _StaveNote46 = new VF.StaveNote({keys: ["B/4"], duration: "16r"});
var _StaveNote47 = new VF.StaveNote({keys: ["F#/4","A/4","D/5"], duration: "16"});
_StaveNote47.addAccidental(0, new VF.Accidental("#"));
var _StaveNote48 = new VF.StaveNote({keys: ["A/4","D/5","F/5"], duration: "16"});
_StaveNote48.addAccidental(2, new VF.Accidental("n"));
var _StaveNote49 = new VF.StaveNote({keys: ["B/4"], duration: "16r"});
var _StaveNote50 = new VF.StaveNote({keys: ["B/4"], duration: "16r"});
var _StaveNote51 = new VF.StaveNote({keys: ["F#/4","A/4","D/5"], duration: "16"});
_StaveNote51.addAccidental(0, new VF.Accidental("#"));
var _StaveNote52 = new VF.StaveNote({keys: ["A/4","D/5","F/5"], duration: "16"});
_StaveNote52.addAccidental(2, new VF.Accidental("n"));
var _StaveNote53 = new VF.StaveNote({keys: ["B/4"], duration: "16r"});
var _StaveNote54 = new VF.StaveNote({keys: ["B/4"], duration: "16r"});
var _StaveNote55 = new VF.StaveNote({keys: ["F#/4","A/4","D/5"], duration: "16"});
_StaveNote55.addAccidental(0, new VF.Accidental("#"));
var _StaveNote56 = new VF.StaveNote({keys: ["A/4","D/5","F/5"], duration: "16"});
_StaveNote56.addAccidental(2, new VF.Accidental("n"));
var _StaveNote57 = new VF.StaveNote({keys: ["B/4"], duration: "16r"});
var _StaveNote58 = new VF.StaveNote({keys: ["B/4"], duration: "16r"});
var __StaveNote_59 = [_StaveNote43,_StaveNote44,_StaveNote45,_StaveNote46,_StaveNote47,_StaveNote48,_StaveNote49,_StaveNote50,_StaveNote51,_StaveNote52,_StaveNote53,_StaveNote54,_StaveNote55,_StaveNote56,_StaveNote57,_StaveNote58];
var _Voice60 = new VF.Voice();
_Voice60.addTickables(__StaveNote_59);
var _Beam62 = VF.Beam.generateBeams(__StaveNote_59);
var _Bar63 = new VF.Stave(10.0, 370, 600.0);
var _StaveNote64 = new VF.StaveNote({keys: ["F#/4","A/4","D/5"], duration: "16"});
_StaveNote64.addAccidental(0, new VF.Accidental("#"));
var _StaveNote65 = new VF.StaveNote({keys: ["A/4","D/5","F/5"], duration: "16"});
_StaveNote65.addAccidental(2, new VF.Accidental("n"));
var _StaveNote66 = new VF.StaveNote({keys: ["B/4"], duration: "16r"});
var _StaveNote67 = new VF.StaveNote({keys: ["B/4"], duration: "16r"});
var _StaveNote68 = new VF.StaveNote({keys: ["F#/4","A/4","D/5"], duration: "16"});
_StaveNote68.addAccidental(0, new VF.Accidental("#"));
var _StaveNote69 = new VF.StaveNote({keys: ["A/4","D/5","F/5"], duration: "16"});
_StaveNote69.addAccidental(2, new VF.Accidental("n"));
var _StaveNote70 = new VF.StaveNote({keys: ["B/4"], duration: "16r"});
var _StaveNote71 = new VF.StaveNote({keys: ["B/4"], duration: "16r"});
var _StaveNote72 = new VF.StaveNote({keys: ["F#/4","A/4","D/5"], duration: "16"});
_StaveNote72.addAccidental(0, new VF.Accidental("#"));
var _StaveNote73 = new VF.StaveNote({keys: ["A/4","D/5","F/5"], duration: "16"});
_StaveNote73.addAccidental(2, new VF.Accidental("n"));
var _StaveNote74 = new VF.StaveNote({keys: ["B/4"], duration: "16r"});
var _StaveNote75 = new VF.StaveNote({keys: ["B/4"], duration: "16r"});
var _StaveNote76 = new VF.StaveNote({keys: ["F#/4","A/4","D/5"], duration: "16"});
_StaveNote76.addAccidental(0, new VF.Accidental("#"));
var _StaveNote77 = new VF.StaveNote({keys: ["A/4","D/5","F/5"], duration: "16"});
_StaveNote77.addAccidental(2, new VF.Accidental("n"));
var _StaveNote78 = new VF.StaveNote({keys: ["B/4"], duration: "16r"});
var _StaveNote79 = new VF.StaveNote({keys: ["B/4"], duration: "16r"});
var __StaveNote_80 = [_StaveNote64,_StaveNote65,_StaveNote66,_StaveNote67,_StaveNote68,_StaveNote69,_StaveNote70,_StaveNote71,_StaveNote72,_StaveNote73,_StaveNote74,_StaveNote75,_StaveNote76,_StaveNote77,_StaveNote78,_StaveNote79];
var _Voice81 = new VF.Voice();
_Voice81.addTickables(__StaveNote_80);
var _Beam83 = VF.Beam.generateBeams(__StaveNote_80);
_Bar0.addClef("treble");
_Bar0.addTimeSignature("4/4");
_Bar0.setContext(ctx).draw();
var _Formatter19 = new VF.Formatter().joinVoices([_Voice18]).format([_Voice18], 600.0 - _Bar0.getNoteStartX());
_Voice18.draw(ctx, _Bar0);
_Beam20.forEach(beam => beam.setContext(ctx).draw());
_Bar21.setContext(ctx).draw();
var _Formatter40 = new VF.Formatter().joinVoices([_Voice39]).format([_Voice39], 600.0 - _Bar21.getNoteStartX());
_Voice39.draw(ctx, _Bar21);
_Beam41.forEach(beam => beam.setContext(ctx).draw());
_Bar42.setContext(ctx).draw();
var _Formatter61 = new VF.Formatter().joinVoices([_Voice60]).format([_Voice60], 600.0 - _Bar42.getNoteStartX());
_Voice60.draw(ctx, _Bar42);
_Beam62.forEach(beam => beam.setContext(ctx).draw());
_Bar63.setContext(ctx).draw();
var _Formatter82 = new VF.Formatter().joinVoices([_Voice81]).format([_Voice81], 600.0 - _Bar63.getNoteStartX());
_Voice81.draw(ctx, _Bar63);
_Beam83.forEach(beam => beam.setContext(ctx).draw());